### ISSUE TITLE
NaN Values in graph courses

### ISSUE THREAD

**Issue by Andreaj42** [JordanFrecon/jordanfrecon.github.io#415]
Hi, 

There are some NaN values on the graph for the section "Teaching Experience". https://jordan-frecon.com/courses/

![Capture d’écran 2023-09-06 à 22 26 17](https://github.com/JordanFrecon/jordanfrecon.github.io/assets/59033540/b33c38c7-a2b9-4677-a601-8497ebc88283)

BR !

**Comment by JordanFrecon** [comment]
I know.. it is quite a messy trick to display horizontal bars with different labels.
Do you have a better solution ? 
Best

**Comment by Andreaj42** [comment]
You may edit the file **get-teaching-exp.html**


```javascript
var barOptions = {
    responsive: false,
    maintainAspectRatio: false,
    interaction: {
        intersect: false,
    },
    scales: {
        yAxes: [{
            ticks: {
                display: true,
                fontColor: textcolor,
            },
            stacked: true,
            gridLines: {
                display: false,
            },
        }],
        xAxes: [{
            ticks: {
                beginAtZero: true
            },
            gridLines: {
                display: false,
            },
        }]
    },
    tooltips: {
        callbacks: {
            label: function (tooltipItem, data) {
		return data.datasets[tooltipItem.datasetIndex].data[tooltipItem.index];
            }
        }
    }
};
```
To get that 
![Capture d’écran 2023-09-10 à 23 47 43](https://github.com/JordanFrecon/jordanfrecon.github.io/assets/59033540/178e6a95-c2ba-45de-830b-00dbdcb77975)

Don't forget to subscribe to [L'Usine Logicielle](https://github.com/L-Usine-Logicielle) 😇

BR !

**Comment by JordanFrecon** [comment]
Wonderful ! Many thanks !
